apiVersion: v1
kind: Template
parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: REPO_NAME
  value: custom-domains-operator
  required: true
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: custom-domains-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
        hive.openshift.io/cluster-platform: aws
    resourceApplyMode: Sync
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-custom-domains-operator
        labels:
          openshift.io/cluster-monitoring: 'true'
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        creationTimestamp: null
        name: custom-domains-operator
      rules:
      - apiGroups:
        - ''
        resources:
        - pods
        - services
        - services/finalizers
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
        - dnses
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - apps
        resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - monitoring.coreos.com
        resources:
        - servicemonitors
        verbs:
        - get
        - create
      - apiGroups:
        - apps
        resourceNames:
        - custom-domains-operator
        resources:
        - deployments/finalizers
        verbs:
        - update
      - apiGroups:
        - managed.openshift.io
        resources:
        - '*'
        verbs:
        - create
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - operator.openshift.io
        resources:
        - ingresscontrollers
        verbs:
        - '*'
      - apiGroups:
        - config.openshift.io
        resources:
        - dnses
        verbs:
        - create
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - dnses.config.openshift.io
        resources:
        - '*'
        verbs:
        - create
        - get
        - list
        - watch
      - apiGroups:
        - dnses.operator.openshift.io
        resources:
        - '*'
        verbs:
        - create
        - get
        - list
        - watch
      - apiGroups:
        - ingress.operator.openshift.io
        resources:
        - dnsrecords
        verbs:
        - get
        - list
        - watch
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: custom-domains-operator
      subjects:
      - kind: ServiceAccount
        name: custom-domains-operator
        namespace: openshift-custom-domains-operator
      roleRef:
        kind: ClusterRole
        name: custom-domains-operator
        apiGroup: rbac.authorization.k8s.io
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: ${REPO_NAME}
      managed.openshift.io/osd: 'true'
    name: custom-domains-operator-crds
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
        hive.openshift.io/cluster-platform: aws
    resourceApplyMode: Sync
    resources:
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: customdomains.managed.openshift.io
      spec:
        additionalPrinterColumns:
        - JSONPath: .status.dnsRecord
          name: DNS Record
          type: string
        group: managed.openshift.io
        names:
          kind: CustomDomain
          listKind: CustomDomainList
          plural: customdomains
          singular: customdomain
        scope: Cluster
        subresources:
          status: {}
        validation:
          openAPIV3Schema:
            description: CustomDomain is the Schema for the customdomains API
            properties:
              apiVersion:
                description: 'APIVersion defines the versioned schema of this representation
                  of an object. Servers should convert recognized schemas to the latest
                  internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                type: string
              kind:
                description: 'Kind is a string value representing the REST resource
                  this object represents. Servers may infer this from the endpoint
                  the client submits requests to. Cannot be updated. In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                type: string
              metadata:
                type: object
              spec:
                description: CustomDomainSpec defines the desired state of CustomDomain
                properties:
                  certificate:
                    description: Certificate points to the custom TLS secret
                    properties:
                      name:
                        description: Name is unique within a namespace to reference
                          a secret resource.
                        type: string
                      namespace:
                        description: Namespace defines the space within which the
                          secret name must be unique.
                        type: string
                    type: object
                  domain:
                    description: This field can be used to define the custom domain
                    type: string
                required:
                - certificate
                - domain
                type: object
              status:
                description: CustomDomainStatus defines the observed state of CustomDomain
                properties:
                  conditions:
                    description: The various conditions for the custom domain
                    items:
                      description: CustomDomainCondition contains details for the
                        current condition of a custom domain
                      properties:
                        lastProbeTime:
                          description: LastProbeTime is the last time we probed the
                            condition.
                          format: date-time
                          type: string
                        lastTransitionTime:
                          description: LastTransitionTime is the laste time the condition
                            transitioned from one status to another.
                          format: date-time
                          type: string
                        message:
                          description: Message is a human-readable message indicating
                            details about last transition.
                          type: string
                        reason:
                          description: Reason is a unique, one-word, CamelCase reason
                            for the condition's last transition.
                          type: string
                        status:
                          description: Status is the status of the condition
                          type: string
                        type:
                          description: Type is the type of the condition.
                          type: string
                      type: object
                    type: array
                  dnsRecord:
                    description: The DNS record for the user to point their external
                      DNS to
                    type: string
                  state:
                    description: The overall state of the custom domain
                    type: string
                required:
                - conditions
                - dnsRecord
                type: object
            type: object
        version: v1alpha1
        versions:
        - name: v1alpha1
          served: true
          storage: true
